name: media_hub
description: "Media Hub â€” universal media grabber, HLS stitcher, smart browser and offline media manager."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  dio: ^5.5.0
  path: ^1.9.0
  path_provider: ^2.1.4
  video_player: ^2.9.1
  chewie: ^1.8.1
  webview_flutter: ^4.8.0
  cached_network_image: ^3.4.0
  share_plus: ^10.1.4
  package_info_plus: ^10.2.1
  cross_file: ^0.3.4
  wakelock_plus: ^1.2.8
  shared_preferences: ^2.2.3
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true